language: node_js
node_js:
  - "10"
skip_cleanup: true
sudo: required
script:
  - npm install
  - npm run lint
  - npm run compile
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  skip-cleanup: true
  local-dir: dist
  target-branch: dist
  keep-history: true
  verbose: true
  on:
    branch: master
