language: node_js
node_js:
  - "8"
  - "9"
cache: yarn
install: yarn
script:
  - yarn lint
  # - yarn test
jobs:
  include:
    - stage: generate lock
      if: tag IS present
      node_js: "8"
      script: yarn compile
      # before_deploy:
      #   - cd dist
      deploy:
        provider: script
        script: bash scripts/deploy.sh
        skip_cleanup: true
        on:
          tags: true
