language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
  yarn: true
skip_cleanup: true
install: yarn
script:
  - yarn lint
  - yarn compile
  - bash scripts/build-lock.sh
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  skip-cleanup: true
  local-dir: dist
  target-branch: dist
  keep-history: true
  verbose: true
  on:
    branch: master
